Traceback (most recent call last):
  File "exceptions.py", line 20, in <module>
    raise Exception('this is the error message')
Exception: this is the error message
Traceback (most recent call last):
  File "exceptions.py", line 24, in <module>
    raise Exception('this is the error message')
Exception: this is the error message
Traceback (most recent call last):
  File "exceptions.py", line 24, in <module>
    raise Exception('this is the error message')
Exception: this is the error message
Traceback (most recent call last):
  File "exceptions.py", line 24, in <module>
    raise Exception('this is the error message')
Exception: this is the error message
Traceback (most recent call last):
  File "exceptions.py", line 24, in <module>
    raise Exception('this is the error message')
Exception: this is the error message
Traceback (most recent call last):
  File "exceptions.py", line 24, in <module>
    raise Exception('this is the error message')
Exception: this is the error message
Traceback (most recent call last):
  File "exceptions.py", line 24, in <module>
    raise Exception('this is the error message')
Exception: this is the error message
